# Description: Configuration file for the project
# 端口号
server:
  port: 8080
spring:
  application:
    # 项目名称
    name: RFID-Archive-Management-System
  # 数据库配置
  datasource:
    username: Encounter
    password: 20020628
    url: jdbc:mysql://127.0.0.1:3306/rams?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      timeout: 50000
      port: 6379
      jedis:
        pool:
          max-active: 3
          max-idle: 3
          min-idle: 1
          max-wait: -1 # 等待时间 -1表示一直等待 直到超时
